app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
index:
    path: /
    defaults: 
        _controller: AppBundle:Default:index
        
listdossier:
    path: /list_dossiers
    defaults: 
        _controller: AppBundle:Default:listDossier
        
listtache:
    path: /list_taches
    defaults: 
        _controller: AppBundle:Default:listTache

listtemps:
    path: /list_temps
    defaults:
        _controller: AppBundle:Default:listTemps

listtempscollaborateur:
    path: /list_temps_collaborateur
    defaults:
        _controller: AppBundle:Default:listTempsCollaborateur

listalltempscollaborateur:
    path: /list_tout_temps_collaborateur
    defaults:
        _controller: AppBundle:Default:listToutTempsCollaborateur
        
adddossier:
    path: /add_dossiers
    defaults:
        _controller: AppBundle:Tables:addDossier
        
addtache:
    path: /add_taches
    defaults:
        _controller: AppBundle:Tables:addTache
        
addtemps:
    path: /add_temps
    defaults:
        _controller: AppBundle:Tables:addTemps
        
moddossier:
    path: /mod_dossier/{id}
    defaults:
        _controller: AppBundle:Tables:modDossier
    requirements:
        id: \d*
        
modtache:
    path: /mod_tache/{id}
    defaults:
        _controller: AppBundle:Tables:modTache
    requirements:
        id: \d*
        
modtemps:
    path: /mod_temps/{id}
    defaults:
        _controller: AppBundle:Tables:modTemps
    requirements:
        id: \d*
        
deldossier:
    path: /del_dossier/{id}
    defaults:
        _controller: AppBundle:Tables:delDossier
    requirements:
        id: \d*
        
deltache:
    path: /del_tache/{id}
    defaults:
        _controller: AppBundle:Tables:delTache
    requirements:
        id: \d*
        
deltemps:
    path: /del_temps/{id}
    defaults:
        _controller: AppBundle:Tables:delTemps
    requirements:
        id: \d*
        
recap:
    path: /recap
    defaults:
        _controller: AppBundle:Default:recap
        
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
listusers:
    path: /listusers
    defaults: 
        _controller: AppBundle:User:listUsers
    
promoteuser:
    path:     /promoteuser/{id}
    defaults:
        _controller: AppBundle:User:promoteUser
    requirements:
        id: \d*
        
demoteuser:
    path:    /demoteuser/{id}
    defaults:
        _controller: AppBundle:User:demoteUser
    requirements:
        id: \d*
        
activateuser:
    path:    /activateuser/{id}
    defaults:
        _controller: AppBundle:User:activateUser
    requirements:
        id: \d*